/**
 * This file was generated by the Jeddict
 */
package br.edu.utfpr.cp.emater.mipdatacollection.domain;

import javax.persistence.Embeddable;

/**
 * @author gabriel
 */
@Embeddable
public class GrowthPhase {

}