/**
 * This file was generated by the Jeddict
 */
package br.edu.utfpr.cp.emater.mipdatacollection.domain;

import javax.persistence.Embedded;
import javax.persistence.Entity;

/**
 * @author gabriel
 */
@Entity
public class Pest extends SampleItem {

    @Embedded
    private PestSize pestSize;

    public PestSize getPestSize() {
        return this.pestSize;
    }

    public void setPestSize(PestSize pestSize) {
        this.pestSize = pestSize;
    }

}