/**
 * This file was generated by the Jeddict
 */
package br.edu.utfpr.cp.emater.mipdatacollection.domain;

import javax.persistence.Basic;
import javax.persistence.Embeddable;

/**
 * @author gabriel
 */
@Embeddable
public class QuestionData {

    @Basic
    private boolean rustResistent;

    @Basic
    private boolean bt;

    public boolean isRustResistent() {
        return this.rustResistent;
    }

    public void setRustResistent(boolean rustResistent) {
        this.rustResistent = rustResistent;
    }

    public boolean isBt() {
        return this.bt;
    }

    public void setBt(boolean bt) {
        this.bt = bt;
    }

}