/**
 * This file was generated by the Jeddict
 */
package br.edu.utfpr.cp.emater.mipdatacollection.domain;

import javax.persistence.Basic;
import javax.persistence.Embeddable;
import javax.persistence.ManyToOne;

/**
 * @author gabriel
 */
@Embeddable
public class SampleEntry {

    @Basic
    private double value;

    @ManyToOne(targetEntity = SampleItem.class)
    private SampleItem sampleItem;

    public double getValue() {
        return this.value;
    }

    public void setValue(double value) {
        this.value = value;
    }

    public SampleItem getSampleItem() {
        return this.sampleItem;
    }

    public void setSampleItem(SampleItem sampleItem) {
        this.sampleItem = sampleItem;
    }

}