/**
 * This file was generated by the Jeddict
 */
package br.edu.utfpr.cp.emater.mipdatacollection.domain;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.persistence.Basic;
import javax.persistence.ElementCollection;
import javax.persistence.Embedded;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * @author gabriel
 */
@Entity
public class Sample {

    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    private Long id;

    @Basic
    @Temporal(TemporalType.DATE)
    private Date sampleDate;

    @Basic
    private int daysAfterEmergence;

    @Basic
    private int defoliation;

    @ElementCollection
    private List<SampleEntry> sampleEntries;

    @Embedded
    private GrowthPhase growthPhase;

    @Embedded
    private SurveyField surveyField;

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Date getSampleDate() {
        return this.sampleDate;
    }

    public void setSampleDate(Date sampleDate) {
        this.sampleDate = sampleDate;
    }

    public int getDaysAfterEmergence() {
        return this.daysAfterEmergence;
    }

    public void setDaysAfterEmergence(int daysAfterEmergence) {
        this.daysAfterEmergence = daysAfterEmergence;
    }

    public int getDefoliation() {
        return this.defoliation;
    }

    public void setDefoliation(int defoliation) {
        this.defoliation = defoliation;
    }

    public List<SampleEntry> getSampleEntries() {
        if (sampleEntries == null) {
            sampleEntries = new ArrayList<>();
        }
        return this.sampleEntries;
    }

    public void setSampleEntries(List<SampleEntry> sampleEntries) {
        this.sampleEntries = sampleEntries;
    }

    public void addSampleEntry(SampleEntry sampleEntry) {
        getSampleEntries().add(sampleEntry);
    }

    public void removeSampleEntry(SampleEntry sampleEntry) {
        getSampleEntries().remove(sampleEntry);
    }

    public GrowthPhase getGrowthPhase() {
        return this.growthPhase;
    }

    public void setGrowthPhase(GrowthPhase growthPhase) {
        this.growthPhase = growthPhase;
    }

    public SurveyField getSurveyField() {
        return this.surveyField;
    }

    public void setSurveyField(SurveyField surveyField) {
        this.surveyField = surveyField;
    }

}