/**
 * This file was generated by the Jeddict
 */
package br.edu.utfpr.cp.emater.mipdatacollection.domain;

import javax.persistence.Basic;
import javax.persistence.Embeddable;

/**
 * @author gabriel
 */
@Embeddable
public class SizeData {

    @Basic
    private double totalArea;

    @Basic
    private double totalPlantedArea;

    @Basic
    private double plantsPerMeter;

    public double getTotalArea() {
        return this.totalArea;
    }

    public void setTotalArea(double totalArea) {
        this.totalArea = totalArea;
    }

    public double getTotalPlantedArea() {
        return this.totalPlantedArea;
    }

    public void setTotalPlantedArea(double totalPlantedArea) {
        this.totalPlantedArea = totalPlantedArea;
    }

    public double getPlantsPerMeter() {
        return this.plantsPerMeter;
    }

    public void setPlantsPerMeter(double plantsPerMeter) {
        this.plantsPerMeter = plantsPerMeter;
    }

}