/**
 * This file was generated by the Jeddict
 */
package br.edu.utfpr.cp.emater.mipdatacollection.domain;

import javax.persistence.Entity;

/**
 * @author gabriel
 */
@Entity
public class Supervisor extends Person {

}