/**
 * This file was generated by the Jeddict
 */
package br.edu.utfpr.cp.emater.mipdatacollection.domain;

import java.util.ArrayList;
import java.util.List;
import javax.persistence.ElementCollection;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToOne;

/**
 * @author gabriel
 */
@Entity
public class Survey {

    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    private Long id;

    @ElementCollection
    private List<SurveyField> surveyFields;

    @OneToOne(targetEntity = Harvest.class)
    private Harvest harvest;

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public List<SurveyField> getSurveyFields() {
        if (surveyFields == null) {
            surveyFields = new ArrayList<>();
        }
        return this.surveyFields;
    }

    public void setSurveyFields(List<SurveyField> surveyFields) {
        this.surveyFields = surveyFields;
    }

    public void addSurveyField(SurveyField surveyField) {
        getSurveyFields().add(surveyField);
    }

    public void removeSurveyField(SurveyField surveyField) {
        getSurveyFields().remove(surveyField);
    }

    public Harvest getHarvest() {
        return this.harvest;
    }

    public void setHarvest(Harvest harvest) {
        this.harvest = harvest;
    }

}