/**
 * This file was generated by the Jeddict
 */
package br.edu.utfpr.cp.emater.mipdatacollection.domain;

import javax.persistence.Basic;
import javax.persistence.Embeddable;
import javax.persistence.Embedded;
import javax.persistence.ManyToOne;

/**
 * @author gabriel
 */
@Embeddable
public class SurveyField {

    @Basic
    private String name;

    @Embedded
    private QuestionData questionData;

    @Embedded
    private DateData dateData;

    @Embedded
    private SizeData sizeData;

    @Embedded
    private LocationData locationData;

    @Embedded
    private ProductivityData productivityData;

    @ManyToOne(targetEntity = Field.class)
    private Field field;

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public QuestionData getQuestionData() {
        return this.questionData;
    }

    public void setQuestionData(QuestionData questionData) {
        this.questionData = questionData;
    }

    public DateData getDateData() {
        return this.dateData;
    }

    public void setDateData(DateData dateData) {
        this.dateData = dateData;
    }

    public SizeData getSizeData() {
        return this.sizeData;
    }

    public void setSizeData(SizeData sizeData) {
        this.sizeData = sizeData;
    }

    public LocationData getLocationData() {
        return this.locationData;
    }

    public void setLocationData(LocationData locationData) {
        this.locationData = locationData;
    }

    public ProductivityData getProductivityData() {
        return this.productivityData;
    }

    public void setProductivityData(ProductivityData productivityData) {
        this.productivityData = productivityData;
    }

    public Field getField() {
        return this.field;
    }

    public void setField(Field field) {
        this.field = field;
    }

}